"""System-mode routing middleware for deterministic, clarification, and emergent execution.

This middleware enables a dual/tri-mode execution policy directly inside DeepAgents:

- deterministic mode (System-1): fast rule-based routing with optional LLM bypass
- clarification mode: ask focused clarification questions before autonomous planning
- emergent mode: LLM-driven planning and tool use

The routing decision can be provided by a custom router callback, or derived from
confidence thresholds in agent state (`confidence_level`).
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import TYPE_CHECKING, Any, Annotated, Callable, Literal, NotRequired, TypedDict

from langchain.agents.middleware.types import (
    AgentMiddleware,
    AgentState,
    ContextT,
    ExtendedModelResponse,
    ModelRequest,
    ModelResponse,
    PrivateStateAttr,
    ResponseT,
)
from langchain_core.messages import AIMessage
from langgraph.types import Command

from deepagents.middleware._utils import append_to_system_message

if TYPE_CHECKING:
    from collections.abc import Awaitable, Callable

    from langchain_core.runnables import RunnableConfig
    from langgraph.runtime import Runtime

logger = logging.getLogger(__name__)

ExecutionMode = Literal["deterministic", "clarification", "emergent"]


class SystemModeDecision(TypedDict, total=False):
    """Router decision payload for system-mode execution.

    Keys:
        mode: One of deterministic/clarification/emergent.
        confidence: Confidence score in range [0.0, 1.0].
        workflow_id: Optional workflow identifier for deterministic route.
        reason: Explanation for audit/debug visibility.
        assistant_message: Optional deterministic response to return without LLM call.
        state_update: Optional state updates to persist when deterministic bypass happens.
    """

    mode: ExecutionMode
    confidence: float
    workflow_id: str
    reason: str
    assistant_message: str
    state_update: dict[str, Any]


class SystemModeState(AgentState):
    """State schema for system-mode routing."""

    execution_mode: NotRequired[ExecutionMode]
    routing_confidence: NotRequired[float]
    routing_reason: NotRequired[str]
    routing_workflow_id: NotRequired[str | None]
    clarification_round: NotRequired[int]
    max_clarification_rounds: NotRequired[int]
    _system_mode_decision: NotRequired[Annotated[SystemModeDecision, PrivateStateAttr]]


class SystemModeStateUpdate(TypedDict):
    """State update generated by SystemModeRoutingMiddleware.before_agent."""

    execution_mode: ExecutionMode
    routing_confidence: float
    routing_reason: str
    routing_workflow_id: str | None
    clarification_round: int
    max_clarification_rounds: int
    _system_mode_decision: SystemModeDecision


SystemModeRouter = Callable[[dict[str, Any]], SystemModeDecision | None]


@dataclass(frozen=True)
class SystemModeConfig:
    """Configuration for system-mode routing behavior."""

    deterministic_threshold: float = 0.85
    clarification_threshold: float = 0.50
    max_clarification_rounds: int = 3


class SystemModeRoutingMiddleware(AgentMiddleware[SystemModeState, ContextT, ResponseT]):
    """Middleware that applies tri-mode routing policy before model planning.

    Routing priority:
    1. Custom router decision, if provided.
    2. Threshold-based mode selection using `confidence_level` from state.

    Deterministic bypass:
    If mode is deterministic and `assistant_message` is provided by the router,
    this middleware returns that response directly without invoking the LLM.
    """

    state_schema = SystemModeState

    def __init__(
        self,
        *,
        router: SystemModeRouter | None = None,
        config: SystemModeConfig | None = None,
    ) -> None:
        self._router = router
        self._config = config or SystemModeConfig()

    def _safe_confidence(self, state: dict[str, Any]) -> float:
        raw = state.get("confidence_level", 0.0)
        try:
            value = float(raw)
        except (TypeError, ValueError):
            return 0.0
        return max(0.0, min(1.0, value))

    def _decide_mode(self, state: dict[str, Any]) -> SystemModeDecision:
        if self._router is not None:
            router_decision = self._router(state)
            if router_decision is not None:
                mode = router_decision.get("mode")
                if mode in {"deterministic", "clarification", "emergent"}:
                    return router_decision

        confidence = self._safe_confidence(state)
        if confidence >= self._config.deterministic_threshold:
            mode: ExecutionMode = "deterministic"
            reason = "confidence_at_or_above_deterministic_threshold"
        elif confidence >= self._config.clarification_threshold:
            mode = "clarification"
            reason = "confidence_in_clarification_band"
        else:
            mode = "emergent"
            reason = "confidence_below_clarification_threshold"

        return SystemModeDecision(
            mode=mode,
            confidence=confidence,
            reason=reason,
            workflow_id=state.get("inferred_workflow") or None,
        )

    def before_agent(
        self,
        state: SystemModeState,
        runtime: Runtime,
        config: RunnableConfig,
    ) -> SystemModeStateUpdate | None:
        decision = self._decide_mode(state)
        mode = decision.get("mode", "emergent")

        clarification_round = int(state.get("clarification_round", 0) or 0)
        max_rounds = int(state.get("max_clarification_rounds", self._config.max_clarification_rounds) or self._config.max_clarification_rounds)

        # Escalate clarification to emergent when max rounds are reached.
        if mode == "clarification" and clarification_round >= max_rounds:
            mode = "emergent"
            escalated = dict(decision)
            escalated["mode"] = "emergent"
            escalated["reason"] = "clarification_round_limit_reached"
            decision = SystemModeDecision(**escalated)

        return SystemModeStateUpdate(
            execution_mode=mode,
            routing_confidence=float(decision.get("confidence", self._safe_confidence(state))),
            routing_reason=decision.get("reason", "router_decision"),
            routing_workflow_id=decision.get("workflow_id"),
            clarification_round=clarification_round,
            max_clarification_rounds=max_rounds,
            _system_mode_decision=decision,
        )

    def _mode_instructions(self, mode: ExecutionMode, decision: SystemModeDecision) -> str:
        if mode == "deterministic":
            workflow = decision.get("workflow_id") or "unknown"
            return (
                "<system_mode>deterministic</system_mode>\n"
                f"- Route selected for workflow: {workflow}\n"
                "- Execute using concise, deterministic behavior.\n"
                "- Avoid exploratory planning unless explicitly blocked."
            )
        if mode == "clarification":
            return (
                "<system_mode>clarification</system_mode>\n"
                "- Ask a focused clarification question before autonomous planning.\n"
                "- Keep it to one concrete question when possible.\n"
                "- If user clarifies intent, proceed with deterministic routing if confidence improves."
            )
        return (
            "<system_mode>emergent</system_mode>\n"
            "- Use autonomous planning and available skills/tools.\n"
            "- Prefer explicit plans for multi-step work.\n"
            "- Keep user-visible updates concise and action-oriented."
        )

    def modify_request(self, request: ModelRequest[ContextT]) -> ModelRequest[ContextT]:
        mode = request.state.get("execution_mode", "emergent")
        decision = request.state.get("_system_mode_decision", {})
        mode_text = self._mode_instructions(mode, decision)
        new_system_message = append_to_system_message(request.system_message, mode_text)
        return request.override(system_message=new_system_message)

    def _try_deterministic_bypass(self, request: ModelRequest[ContextT]) -> ExtendedModelResponse[ResponseT] | None:
        mode = request.state.get("execution_mode")
        if mode != "deterministic":
            return None

        decision: SystemModeDecision = request.state.get("_system_mode_decision", {})
        assistant_message = decision.get("assistant_message")
        if not assistant_message:
            return None

        model_response: ModelResponse[ResponseT] = ModelResponse(result=[AIMessage(content=assistant_message)])

        command_update: dict[str, Any] = {
            "execution_mode": "deterministic",
            "routing_confidence": decision.get("confidence", request.state.get("routing_confidence", 0.0)),
            "routing_workflow_id": decision.get("workflow_id", request.state.get("routing_workflow_id")),
        }
        if isinstance(decision.get("state_update"), dict):
            command_update.update(decision["state_update"])

        return ExtendedModelResponse(
            model_response=model_response,
            command=Command(update=command_update),
        )

    def wrap_model_call(
        self,
        request: ModelRequest[ContextT],
        handler: Callable[[ModelRequest[ContextT]], ModelResponse[ResponseT]],
    ) -> ModelResponse[ResponseT] | ExtendedModelResponse[ResponseT]:
        bypass_response = self._try_deterministic_bypass(request)
        if bypass_response is not None:
            return bypass_response

        modified_request = self.modify_request(request)
        return handler(modified_request)

    async def awrap_model_call(
        self,
        request: ModelRequest[ContextT],
        handler: Callable[[ModelRequest[ContextT]], Awaitable[ModelResponse[ResponseT]]],
    ) -> ModelResponse[ResponseT] | ExtendedModelResponse[ResponseT]:
        bypass_response = self._try_deterministic_bypass(request)
        if bypass_response is not None:
            return bypass_response

        modified_request = self.modify_request(request)
        return await handler(modified_request)
