"""System-mode routing middleware for deterministic, clarification, and emergent execution.

This middleware enables a dual/tri-mode execution policy directly inside DeepAgents:

- deterministic mode (System-1): fast rule-based routing with optional LLM bypass
- clarification mode: ask focused clarification questions before autonomous planning
- emergent mode: LLM-driven planning and tool use

The routing decision can be provided by a custom router callback, or derived from
confidence thresholds in agent state (`confidence_level`).
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import TYPE_CHECKING, Any, Annotated, Callable, Literal, NotRequired, TypedDict

from langchain.agents.middleware.types import (
    AgentMiddleware,
    AgentState,
    ContextT,
    ModelRequest,
    ModelResponse,
    PrivateStateAttr,
    ResponseT,
    hook_config,
)
from langchain_core.messages import AIMessage

from deepagents.middleware._utils import append_to_system_message

if TYPE_CHECKING:
    from collections.abc import Awaitable, Callable

    from langchain_core.runnables import RunnableConfig
    from langgraph.runtime import Runtime

logger = logging.getLogger(__name__)

ExecutionMode = Literal["deterministic", "clarification", "emergent"]


class SystemModeDecision(TypedDict, total=False):
    """Router decision payload for system-mode execution.

    Keys:
        mode: One of deterministic/clarification/emergent.
        confidence: Confidence score in range [0.0, 1.0].
        workflow_id: Optional workflow identifier for deterministic route.
        reason: Explanation for audit/debug visibility.
        assistant_message: Optional deterministic response to return without LLM call.
        forced_tool_calls: Optional list of tool call dicts to force-execute without LLM.
            Each dict must have ``id``, ``name``, ``args``, and ``type`` keys.
            When provided, takes precedence over ``assistant_message``.
            The middleware injects these as an ``AIMessage`` in ``before_model`` and jumps
            directly to the ``tools`` node, bypassing the ``model`` node entirely.
        state_update: Optional state updates to persist when deterministic bypass happens.
    """

    mode: ExecutionMode
    confidence: float
    workflow_id: str
    reason: str
    assistant_message: str
    forced_tool_calls: list[dict[str, Any]]
    state_update: dict[str, Any]


class SystemModeState(AgentState):
    """State schema for system-mode routing."""

    execution_mode: NotRequired[ExecutionMode]
    routing_confidence: NotRequired[float]
    routing_reason: NotRequired[str]
    routing_workflow_id: NotRequired[str | None]
    clarification_round: NotRequired[int]
    max_clarification_rounds: NotRequired[int]
    _system_mode_decision: NotRequired[Annotated[SystemModeDecision, PrivateStateAttr]]


class SystemModeStateUpdate(TypedDict):
    """State update generated by SystemModeRoutingMiddleware.before_agent."""

    execution_mode: ExecutionMode
    routing_confidence: float
    routing_reason: str
    routing_workflow_id: str | None
    clarification_round: int
    max_clarification_rounds: int
    _system_mode_decision: SystemModeDecision


SystemModeRouter = Callable[[dict[str, Any]], SystemModeDecision | None]


@dataclass(frozen=True)
class SystemModeConfig:
    """Configuration for system-mode routing behavior."""

    deterministic_threshold: float = 0.85
    clarification_threshold: float = 0.50
    max_clarification_rounds: int = 3


class SystemModeRoutingMiddleware(AgentMiddleware[SystemModeState, ContextT, ResponseT]):
    """Middleware that applies tri-mode routing policy before model planning.

    Routing priority:
    1. Custom router decision, if provided.
    2. Threshold-based mode selection using `confidence_level` from state.

    Deterministic bypass (System-1):
    When mode is ``deterministic`` and the router decision contains
    ``forced_tool_calls``, the ``before_model`` hook injects a synthetic
    ``AIMessage`` carrying those tool calls and sets ``jump_to="tools"``.
    The LangGraph engine therefore **skips the ``model`` node entirely** and
    routes straight to the ``tools`` node.

    When ``assistant_message`` is set instead, ``before_model`` injects the
    message and sets ``jump_to="end"``, skipping both model and tools.
    """

    state_schema = SystemModeState

    def __init__(
        self,
        *,
        router: SystemModeRouter | None = None,
        config: SystemModeConfig | None = None,
    ) -> None:
        self._router = router
        self._config = config or SystemModeConfig()

    def _safe_confidence(self, state: dict[str, Any]) -> float:
        raw = state.get("confidence_level", 0.0)
        try:
            value = float(raw)
        except (TypeError, ValueError):
            return 0.0
        return max(0.0, min(1.0, value))

    def _decide_mode(self, state: dict[str, Any]) -> SystemModeDecision:
        if self._router is not None:
            router_decision = self._router(state)
            if router_decision is not None:
                mode = router_decision.get("mode")
                if mode in {"deterministic", "clarification", "emergent"}:
                    return router_decision

        confidence = self._safe_confidence(state)
        if confidence >= self._config.deterministic_threshold:
            mode: ExecutionMode = "deterministic"
            reason = "confidence_at_or_above_deterministic_threshold"
        elif confidence >= self._config.clarification_threshold:
            mode = "clarification"
            reason = "confidence_in_clarification_band"
        else:
            mode = "emergent"
            reason = "confidence_below_clarification_threshold"

        return SystemModeDecision(
            mode=mode,
            confidence=confidence,
            reason=reason,
            workflow_id=state.get("inferred_workflow") or None,
        )

    def before_agent(
        self,
        state: SystemModeState,
        runtime: Runtime,
        config: RunnableConfig,
    ) -> SystemModeStateUpdate | None:
        decision = self._decide_mode(state)
        mode = decision.get("mode", "emergent")

        clarification_round = int(state.get("clarification_round", 0) or 0)
        max_rounds = int(state.get("max_clarification_rounds", self._config.max_clarification_rounds) or self._config.max_clarification_rounds)

        # Escalate clarification to emergent when max rounds are reached.
        if mode == "clarification" and clarification_round >= max_rounds:
            mode = "emergent"
            escalated = dict(decision)
            escalated["mode"] = "emergent"
            escalated["reason"] = "clarification_round_limit_reached"
            decision = SystemModeDecision(**escalated)

        return SystemModeStateUpdate(
            execution_mode=mode,
            routing_confidence=float(decision.get("confidence", self._safe_confidence(state))),
            routing_reason=decision.get("reason", "router_decision"),
            routing_workflow_id=decision.get("workflow_id"),
            clarification_round=clarification_round,
            max_clarification_rounds=max_rounds,
            _system_mode_decision=decision,
        )

    def _mode_instructions(self, mode: ExecutionMode, decision: SystemModeDecision) -> str:
        if mode == "deterministic":
            workflow = decision.get("workflow_id") or "unknown"
            return (
                "<system_mode>deterministic</system_mode>\n"
                f"- Route selected for workflow: {workflow}\n"
                "- Execute using concise, deterministic behavior.\n"
                "- Avoid exploratory planning unless explicitly blocked."
            )
        if mode == "clarification":
            return (
                "<system_mode>clarification</system_mode>\n"
                "- Ask a focused clarification question before autonomous planning.\n"
                "- Keep it to one concrete question when possible.\n"
                "- If user clarifies intent, proceed with deterministic routing if confidence improves."
            )
        return (
            "<system_mode>emergent</system_mode>\n"
            "- Use autonomous planning and available skills/tools.\n"
            "- Prefer explicit plans for multi-step work.\n"
            "- Keep user-visible updates concise and action-oriented."
        )

    @hook_config(can_jump_to=["tools", "end"])
    def before_model(
        self,
        state: SystemModeState,
        runtime: Runtime,
        config: RunnableConfig,
    ) -> dict[str, Any] | None:
        """System-1 bypass: skip the model node entirely for deterministic routes.

        - ``forced_tool_calls`` → injects AIMessage with tool_calls + ``jump_to="tools"``.
          The model node is never executed; tool dispatch happens directly.
        - ``assistant_message`` → injects AIMessage with text content + ``jump_to="end"``.
          Both model and tools nodes are skipped.
        - Otherwise → returns ``None`` (falls through to model for emergent/clarification).
        """
        mode = state.get("execution_mode")
        if mode != "deterministic":
            return None

        decision: SystemModeDecision = state.get("_system_mode_decision", {})

        # Forced tool calls — true System-1 fast-path.
        # Injects tool calls directly, bypassing the model node.
        forced_tool_calls = decision.get("forced_tool_calls")
        if forced_tool_calls:
            logger.info(
                "System-1 bypass (before_model): forced_tool_calls=%s (reason=%s)",
                [tc.get("name") for tc in forced_tool_calls],
                decision.get("reason", "unknown"),
            )
            update: dict[str, Any] = {
                "messages": [AIMessage(content="", tool_calls=forced_tool_calls)],
                "jump_to": "tools",
                "execution_mode": "deterministic",
                "routing_confidence": decision.get("confidence", state.get("routing_confidence", 0.0)),
                "routing_workflow_id": decision.get("workflow_id", state.get("routing_workflow_id")),
            }
            if isinstance(decision.get("state_update"), dict):
                update.update(decision["state_update"])
            return update

        # Text-only bypass — skip model and tools, go directly to end.
        assistant_message = decision.get("assistant_message")
        if assistant_message:
            logger.info(
                "System-1 bypass (before_model): assistant_message (reason=%s)",
                decision.get("reason", "unknown"),
            )
            update = {
                "messages": [AIMessage(content=assistant_message)],
                "jump_to": "end",
                "execution_mode": "deterministic",
                "routing_confidence": decision.get("confidence", state.get("routing_confidence", 0.0)),
                "routing_workflow_id": decision.get("workflow_id", state.get("routing_workflow_id")),
            }
            if isinstance(decision.get("state_update"), dict):
                update.update(decision["state_update"])
            return update

        return None

    async def abefore_model(
        self,
        state: SystemModeState,
        runtime: Runtime,
        config: RunnableConfig,
    ) -> dict[str, Any] | None:
        """Async variant — delegates to sync before_model (all logic is synchronous)."""
        return self.before_model(state, runtime, config)

    def modify_request(self, request: ModelRequest[ContextT]) -> ModelRequest[ContextT]:
        """Inject system-mode instructions into the system prompt for non-bypass paths."""
        mode = request.state.get("execution_mode", "emergent")
        decision = request.state.get("_system_mode_decision", {})
        mode_text = self._mode_instructions(mode, decision)
        new_system_message = append_to_system_message(request.system_message, mode_text)
        return request.override(system_message=new_system_message)

    def wrap_model_call(
        self,
        request: ModelRequest[ContextT],
        handler: Callable[[ModelRequest[ContextT]], ModelResponse[ResponseT]],
    ) -> ModelResponse[ResponseT]:
        """Inject mode instructions into the system prompt, then call the model.

        Bypass cases (forced_tool_calls / assistant_message) are handled in
        ``before_model`` before this is ever reached.
        """
        return handler(self.modify_request(request))

    async def awrap_model_call(
        self,
        request: ModelRequest[ContextT],
        handler: Callable[[ModelRequest[ContextT]], Awaitable[ModelResponse[ResponseT]]],
    ) -> ModelResponse[ResponseT]:
        """Async variant of wrap_model_call."""
        return await handler(self.modify_request(request))
